# For more info, please visit
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3"

services:
  # For more info, please visit https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  es:
    # Find a version at https://github.com/elastic/elasticsearch/tags
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

## Uncomment below if you have an external attachable network.
# networks:
#   default:
#     external:
#       name: public
