# For more info, please visit
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3"

services:
  # For more info, please visit https://hub.docker.com/r/fluent/fluentd
  fluentd:
    image: uzxmx/fluentd:1.12.1
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./conf:/fluentd/etc

## Uncomment below if you have an external attachable network.
# networks:
#   default:
#     external:
#       name: public
