# For more info, please visit
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3"

services:
  # For more info, please visit https://hub.docker.com/_/redis
  redis:
    image: redis:5.0.12
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

## Uncomment below if you have an external attachable network.
# networks:
#   default:
#     external:
#       name: public
