# For more info, please visit
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.4"

services:
  # For more info, please visit https://hub.docker.com/_/nginx
  nginx:
    image: nginx:1.19.6-alpine
    restart: always
    # This doesn't work on Mac OSX.
    # network_mode: host
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./include.d:/etc/nginx/include.d
      - ./site:/site
      # - /etc/certs:/etc/certs
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: pause
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

## Uncomment below if you have an external attachable network.
# networks:
#   default:
#     external:
#       name: public
