# For more info, please visit
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3"

services:
  # For more info, please visit https://hub.docker.com/_/mysql
  mysql:
    image: mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
    restart: always
    # Disable ONLY_FULL_GROUP_BY.
    # Ref: https://stackoverflow.com/q/41887460
    command: --sql_mode=""
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Use `/tmp/shared` as a mount point for shared files, so we don't need to
      # copy files into the container.
      - /tmp/shared:/tmp/shared
    ports:
      - "3306:3306"
    deploy:
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#placement
      # https://docs.docker.com/engine/swarm/services/#placement-constraints
      placement:
        constraints:
          - "node.role==manager"
          - "engine.labels.operatingsystem==ubuntu 18.04"
        preferences:
          - spread: node.labels.zone

## Uncomment below if you have an external attachable network.
# networks:
#   default:
#     external:
#       name: public
