# For more info, please visit
# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3"

services:
  # Do not use `_` in the service name. Servers such as Tomcat may return
  # 400 bad request because of the invalid Host header.
  # Host name can only contain alphanumeric(a-zA-Z0-9), hyphen(-) and period(.).
  mongo:
    # For more info, please visit https://hub.docker.com/_/mongo
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=YOUR_PASSWORD
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

## Uncomment below if you have an external attachable network.
# networks:
#   default:
#     external:
#       name: public
